from datetime import datetime

class ScheduleRepository:
    def __init__(self, supabase):
        self.supabase = supabase

    # -------------------------
    # CREATE SCHEDULE
    # -------------------------
    def create_schedule(self, user_id):

        # Set old to false
        (self.supabase
         .table("Schedules")
         .update({"is_active": False})
         .eq("user_id", user_id)
         .eq("is_active", True)
         .execute()
        )

        result = self.supabase.table("Schedules").insert({
            "user_id": user_id,
            "name": "Generated Schedule",
            "date": datetime.now().date().isoformat(),
            "is_active": True
        }).execute()

        return result.data[0]


    # -------------------------
    # INSERT BLOCKS (BULK)
    # -------------------------
    def insert_blocks(self, blocks: list):
        result = self.supabase.table("ScheduleBlocks").insert(blocks).execute()
        return result.data  # includes IDs generated by DB


    # -------------------------
    # FETCH ACTIVE SCHEDULE
    # -------------------------
    def get_active_schedule(self, user_id):
        result = (
            self.supabase
            .table("Schedules")
            .select("*, ScheduleBlocks(*)")
            .eq("user_id", user_id)
            .eq("is_active", True)
            .limit(1)
            .execute()
        )

        if not result.data:
            return None

        schedule = result.data[0]

        # reshape for frontend
        return {
            "id": schedule["id"],
            "blocks": [
                {
                    "id": block["id"],
                    "taskId": block["task_id"],
                    "title": block["title"],
                    "start": block["start_time"],
                    "end": block["end_time"],
                    "color": block.get("color")
                }
                for block in schedule.get("ScheduleBlocks", [])
            ]
        }